name: Publish Release Package
on:
  push:
    branches:
      - "releases/**"
jobs:
  publish:
    name: Package Release
    runs-on: ubuntu-latest
    env:
        NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
          dotnet-quality: 'preview'
      - name: Install dependencies
        run: dotnet restore src
      - name: Package
        run: dotnet pack --no-restore -o .
      - name: Publish to Nuget
        env:
          NUGET_KEY: ${{ secrets.DEPLOY_KEY }}
          NUGET_API: https://api.nuget.org/v3/index.json
        run: dotnet nuget push CSTNet.*.nupkg --api-key $NUGET_KEY --source $NUGET_API
